# Generated by Django 3.2.4 on 2021-06-05 20:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('NA', 'NA')], default='NA', max_length=100)),
                ('is_cough', models.BooleanField(default=False)),
                ('is_fever', models.BooleanField(default=False)),
                ('is_sore_throat', models.BooleanField(default=False)),
                ('is_shortness_of_breath', models.BooleanField(default=False)),
                ('is_head_ache', models.BooleanField(default=False)),
                ('is_age_60_and_above', models.BooleanField(default=False)),
                ('is_contact', models.BooleanField(default=False)),
                ('used_prediction', models.BooleanField(default=False)),
                ('prediction_score', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('beds', models.IntegerField()),
                ('oxygen_cylinders', models.IntegerField(null=True)),
                ('wards', models.IntegerField(null=True)),
                ('curr_patients', models.IntegerField(null=True)),
                ('citizen_watchlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='main_app.citizenmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Hospital', models.BooleanField(default=False)),
                ('is_Citizen', models.BooleanField(default=False)),
                ('unit', models.CharField(choices=[('Hospital', 'Hospital'), ('Citizen', 'Citizen'), ('NA', 'NA')], default='NA', max_length=100)),
                ('unit_name', models.CharField(default='None', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_requested', models.CharField(max_length=200, null=True)),
                ('name_received', models.CharField(max_length=200, null=True)),
                ('beds_requested', models.IntegerField()),
                ('approved_status', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('oxygen_cylinders_requested', models.IntegerField()),
                ('contact_email', models.EmailField(max_length=200, null=True)),
                ('contact_phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('hospital_asked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asked_requests', to='main_app.hospital')),
                ('hospital_received', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='main_app.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_hospital', to='main_app.usermodel'),
        ),
        migrations.CreateModel(
            name='DateCaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('cases', models.IntegerField()),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_case', to='main_app.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='citizenmodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_citizen', to='main_app.usermodel'),
        ),
    ]
